apiVersion: v1
kind: Service
metadata:
  name: cm-controller-manager-metrics-service-plain
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
