apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlogic-operator
  namespace: system
  labels:
    control-plane: kuberlogic-operator
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: manager
          env:
            - name: IMG_REPO
              value: gitlab.corp.cloudlinux.com:5001/cloudmanaged/cloudmanaged/
            - name: IMG_PULL_SECRET
              value: gitlab-registry
        - name: apiserver
          env:
            - name: KUBERLOGIC_AUTH_PROVIDER
              value: none