apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberlogic-operator
  namespace: system
  labels:
    control-plane: kuberlogic-operator
spec:
  template:
    spec:
      imagePullSecrets:
        - name: kuberlogic-registry
      containers:
        - name: manager
          env:
            - name: IMG_REPO
              value: quay.io/kuberlogic
            - name: IMG_PULL_SECRET
              value: kuberlogic-registry
        - name: apiserver
          env:
            - name: KUBERLOGIC_AUTH_PROVIDER
              value: none