apiVersion: v1
kind: Service
metadata:
  name: kuberlogic-apiserver
spec:
  type: NodePort
  selector:
    control-plane: kuberlogic-operator
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30007