{{ if .Values.updater.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.updater.cronjob.name }}
spec:
  schedule: {{ .Values.updater.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: kuberlogic-updater
          labels:
            app: kuberlogic-updater
        spec:
          serviceAccountName: {{ .Values.updater.serviceAccount.name }}
          {{- with .Values.imagePullSecret  }}
          imagePullSecrets:
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          containers:
            - name: updater
              env:
                - name: REGISTRY_API
                  value: {{ .Values.updater.config.registryApi }}
              image: {{ .Values.image.repository }}:{{ .Values.updater.image.tag | default .Chart.AppVersion }}
          restartPolicy: OnFailure
{{- end }}