apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mailservice
  template:
    metadata:
      labels:
        name: mailservice
    spec:
      containers:
        - name: mailservice
          # Replace this with the built image name
          image: quay.io/datadarius/tiny-mailcatcher:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 1025
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 1025
              protocol: TCP
              name: smtp
            - containerPort: 1080
              protocol: TCP
              name: web
---
kind: Service
apiVersion: v1
metadata:
  name: mailservice
spec:
  selector:
    name: mailservice
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP