---
debugLogs: true
# kubeconfigPath: ~/.kube/config # must be full path to Kubeconfig

# required values
namespace: kuberlogic
registry:
  server: https://quay.io
  username: quayusername
  password: quaypassword

endpoints:
  api: kuberlogic.com
  ui: kuberlogic.com
  monitoringConsole: mc.kuberlogic.com

auth:
  testUserPassword: testPassword
  adminPassword: secret
