apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- services.yaml

configMapGenerator:
- behavior: create
  env: backups.properties
  name: kuberlogic-backup-properties
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - docker-compose.yaml
  name: compose-file
secretGenerator:
- behavior: create
  env: apiserver.properties
  name: apiserver
- behavior: create
  literals:
  - chargebee_site=
  - chargebee_key=
  - kuberlogic_domain=example.com
  name: chargebee-integration
images:
- name: apiserver
  newName: quay.io/kuberlogic/dynamic-apiserver
  newTag: 0.0.9
- name: chargebee-integration
  newName: quay.io/kuberlogic/chargebee-integration
  newTag: 0.0.9
- name: controller
  newName: quay.io/kuberlogic/dynamic-operator
  newTag: 0.0.9
