# permissions for end users to view cloudmanageds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberlogic-viewer-role
rules:
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogics/status
  verbs:
  - get
