# permissions for end users to edit cloudmanageds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberlogic-editor-role
rules:
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberlogic.com
  resources:
  - kuberlogics/status
  verbs:
  - get
