---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - cloudlinux.com
    resources:
      - cloudmanageds
      - cloudmanagedbackups
      - postgresqls
      - mysqlclusters
      - redisfailovers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudlinux.com
    resources:
      - cloudmanageds/status
      - cloudmanagedbackups/status
    verbs:
      - get
      - patch
      - update
  # for backups:
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch