apiVersion: kuberlogic.com/v1
kind: KuberLogicBackupRestore
metadata:
  name: klr-mysql
spec:
  type: s3
  name: kuberlogic-my
  secret: do-s3
  backup: s3://kuberlogic/mysql/kuberlogic-my/logical_backups/bar-1605520343.tar.gz
  database: "bar"