apiVersion: kuberlogic.com/v1
kind: KuberLogicBackupRestore
metadata:
  name: klr-postgresql
spec:
  type: s3
  name: kuberlogic-pg
  secret: do-s3
  # full
  # https://kuberlogic.fra1.digitaloceanspaces.com/postgresql/cloudmanaged-pg/logical_backups/1605860851.sql.gz
  # specific db
  # https://kuberlogic.fra1.digitaloceanspaces.com/postgresql/cloudmanaged-pg/logical_backups/bar-1605860741.sql.gz
  backup: s3://kuberlogic/postgresql/kuberlogic-pg/logical_backups/bar-1605860741.sql.gz
  database: "bar"