apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.cloudlinux.com
  labels:
    app: mysql-operator
spec:
  group: cloudlinux.com
  names:
    kind: MysqlBackup
    listKind: MysqlBackupList
    plural: mysqlbackups
    singular: mysqlbackup
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
