apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.cloudlinux.com
  labels:
    app: mysql-operator
spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type == 'Ready')].status
      description: The cluster status
      name: Ready
      type: string
    - JSONPath: .spec.replicas
      description: The number of desired nodes
      name: Replicas
      type: integer
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: cloudlinux.com
  names:
    kind: MysqlCluster
    listKind: MysqlClusterList
    plural: mysqlclusters
    shortNames:
      - mysql
    singular: mysqlcluster
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.readyNodes
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
