---
apiVersion: v1
kind: Service
metadata:
  name: mysql-operator-0-svc
  labels:
    app: mysql-operator
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 3000
    - name: raft
      port: 10008
      targetPort: 10008
  selector:
    statefulset.kubernetes.io/pod-name: mysql-operator-0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
spec:
  type: ClusterIP
  selector:
    app: mysql-operator
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
