apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: redis-operator
    newName: quay.io/kuberlogic/redis-operator
    newTag: latest
patchesStrategicMerge:
  - patches/regcred.yaml
resources:
  - operator-service-account-rbac.yaml
  - deployment.yaml

