---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Values.kong.jwt2headerPlugin.name }}
  namespace: {{ .Release.Namespace }}
config:
  token_required: true
  query_arg: {{ .Values.jwtAuth.param }}
plugin: jwt2header-plugin