---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Values.kong.authPlugin }}
  namespace: {{ .Release.Namespace }}
config:
  secret_is_base64: false
  run_on_preflight: true
  key_claim_name: iss
  uri_param_names:
    - {{ .Values.jwtAuth.param }}
plugin: jwt
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
  name: {{ .Values.kong.authPlugin }}
  namespace: {{ .Release.Namespace }}
username: {{ .Values.kong.authPlugin }}
credentials:
  - {{ .Values.kong.authPlugin }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kong.authPlugin }}
  namespace: {{ .Release.Namespace }}
data:
  algorithm: {{ .Values.jwtAuth.algorithm | b64enc | quote }}
  key: {{ .Values.jwtAuth.iss | b64enc | quote }}
  kongCredType: {{ .Values.authType | b64enc | quote  }}
  rsa_public_key: {{ .Values.jwtAuth.rsaPubKey | b64enc | quote }}