apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: kuberlogic-updater
          labels:
            app: kuberlogic-updater
        spec:
          serviceAccountName: kuberlogic-updater
          containers:
            - name: updater
              image: updater:latest
          restartPolicy: OnFailure
