apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: updater
    newName: gitlab.corp.cloudlinux.com:5001/cloudmanaged/cloudmanaged/cloudmanaged-updater
    newTag: latest
patchesStrategicMerge:
  - patches/regcred.yaml
  - patches/gitlab-env.yaml
resources:
  - cronjob.yaml
  - service-account-rbac.yaml