---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: {{ .Values.nodePortService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: keycloak
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: keycloak
    component: keycloak
  type: NodePort